# Generated by Django 3.1 on 2020-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='moive_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
