# Generated by Django 3.1 on 2020-08-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieInfo', '0003_auto_20200825_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='moive_desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='release_date',
            field=models.DateField(),
        ),
    ]
