# Generated by Django 3.1 on 2020-08-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieInfo', '0004_auto_20200825_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
